In [35]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder , OneHotEncoder
import pickle

In [36]:
## Reading our csv files 
data= pd.read_csv(r'C:\Users\nahid\Desktop\DeepLearning Project\Data\Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [37]:
## Process the data
data = data.drop(['RowNumber','CustomerId','Surname'], axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [38]:
## Onehotcoder 
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder_columns = onehot_encoder_geo.get_feature_names_out(['Geography'])
geo_encoder_array = geo_encoder.toarray()
geo_encoder_df = pd.DataFrame(geo_encoder_array, columns= geo_encoder_columns)
geo_encoder_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [39]:
## Combine one hot encoder columns with the original data
data= pd.concat([data.drop('Geography', axis=1), geo_encoder_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,Female,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,Female,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,Female,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,Female,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,Female,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [40]:
## Encode categorical variables 
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data.head(10)

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
5,645,1,44,8,113755.78,2,1,0,149756.71,1,0.0,0.0,1.0
6,822,1,50,7,0.00,2,1,1,10062.80,0,1.0,0.0,0.0
7,376,0,29,4,115046.74,4,1,0,119346.88,1,0.0,1.0,0.0
8,501,1,44,4,142051.07,2,0,1,74940.50,0,1.0,0.0,0.0
9,684,1,27,2,134603.88,1,1,1,71725.73,0,1.0,0.0,0.0

In [41]:
## Divide the dataset into independent and dependent featuers 
X= data.drop(['EstimatedSalary'],axis=1)
y=data['EstimatedSalary']

In [42]:
## Split the data in training and testing sets
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [43]:
## Scale these featuers
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [44]:
## Save the encoders and sscaler 
with open('label_encoder_gender_reg.pkl','wb') as file :
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo_reg.pkl','wb') as file :
    pickle.dump(onehot_encoder_geo,file)

## Save the scaler file in the pkl formet 
with open('scaler_reg.pkl','wb') as file:
    pickle.dump(scaler,file)

## ANN Implementetion

In [45]:
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [46]:
## Build our ANN  model 
model = Sequential(
    [
        Dense(64,activation='relu',input_shape =(X_train.shape[1],)), ## HL1 connect with input layer
        Dense(32,activation='relu'), #HL2
        Dense(1) # linear  regression
    ] 
)

## compile the model 
model.compile(optimizer = 'adam', loss = 'mean_absolute_error',metrics =['mae'])
model.summary()

c:\Users\nahid\Desktop\DeepLearning Project\venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [47]:
## Set up TensorBord
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
log_dir = "regression_log1/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [48]:
## Set up Early Stopping 
early_stopping_callback = EarlyStopping(monitor='val_loss',patience= 10, restore_best_weights= True)

In [49]:
## Training the model 
history = model.fit(
    X_train,y_train, 
    validation_data = (X_test,y_test), epochs = 100,
    callbacks = [early_stopping_callback,tensorflow_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 101074.0078 - mae: 101074.0078 - val_loss: 98557.4141 - val_mae: 98557.4141
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - loss: 99391.4062 - mae: 99391.4062 - val_loss: 97220.5938 - val_mae: 97220.5938
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - loss: 99280.4141 - mae: 99280.4141 - val_loss: 93699.5781 - val_mae: 93699.5781
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1000us/step - loss: 93161.0469 - mae: 93161.0469 - val_loss: 87693.0469 - val_mae: 87693.0469
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - loss: 88027.3438 - mae: 88027.3438 - val_loss: 79789.5703 - val_mae: 79789.5703
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - loss: 78404.9766 - mae: 78404.9766 - val_loss: 71123.3828 - val_mae: 71123.3828
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - loss: 70062.5938 - mae: 70062.5938 - val_loss: 63285.9258 - val_mae: 63285.9258
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - loss: 61675.5039 - mae: 61675.5039 - val_loss: 57252.0430 - val_mae: 57252.0430
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 56860.7148 - mae: 56860.7148 - val_loss: 53433.1094 - val_mae: 53433.1094
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - loss: 53173.2578 - mae: 53173.2578 - val_loss: 51517.6523 - val_mae: 51517.6523
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - loss: 51108.9766 - mae: 51108.9766 - val_loss: 50815.7383 - val_mae: 50815.7383
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50535.7188 - mae: 50535.7188 - val_loss: 50619.8203 - val_mae: 50619.8203
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50532.0625 - mae: 50532.0625 - val_loss: 50557.5664 - val_mae: 50557.5664
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50564.7422 - mae: 50564.7422 - val_loss: 50529.1445 - val_mae: 50529.1445
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50131.0273 - mae: 50131.0273 - val_loss: 50492.6680 - val_mae: 50492.6680
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - loss: 50022.1562 - mae: 50022.1562 - val_loss: 50462.6641 - val_mae: 50462.6641
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50079.2070 - mae: 50079.2070 - val_loss: 50427.4141 - val_mae: 50427.4141
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50243.0859 - mae: 50243.0859 - val_loss: 50404.8867 - val_mae: 50404.8867
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - loss: 49490.3477 - mae: 49490.3477 - val_loss: 50385.0078 - val_mae: 50385.0078
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - loss: 50035.2891 - mae: 50035.2891 - val_loss: 50366.8594 - val_mae: 50366.8594
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49945.4570 - mae: 49945.4570 - val_loss: 50348.9258 - val_mae: 50348.9258
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50553.4375 - mae: 50553.4375 - val_loss: 50332.9609 - val_mae: 50332.9609
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - loss: 49924.5625 - mae: 49924.5625 - val_loss: 50320.0273 - val_mae: 50320.0273
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - loss: 50134.3125 - mae: 50134.3125 - val_loss: 50309.8555 - val_mae: 50309.8555
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - loss: 49621.9570 - mae: 49621.9570 - val_loss: 50298.6172 - val_mae: 50298.6172
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - loss: 50044.9336 - mae: 50044.9336 - val_loss: 50283.6680 - val_mae: 50283.6680
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - loss: 49865.4180 - mae: 49865.4180 - val_loss: 50275.0742 - val_mae: 50275.0742
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - loss: 49983.0391 - mae: 49983.0391 - val_loss: 50268.1992 - val_mae: 50268.1992
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - loss: 49422.5000 - mae: 49422.5000 - val_loss: 50259.3281 - val_mae: 50259.3281
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - loss: 49645.8164 - mae: 49645.8164 - val_loss: 50258.9570 - val_mae: 50258.9570
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - loss: 49433.0508 - mae: 49433.0508 - val_loss: 50264.2812 - val_mae: 50264.2812
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 996us/step - loss: 50021.3359 - mae: 50021.3359 - val_loss: 50245.6875 - val_mae: 50245.6875
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49713.4531 - mae: 49713.4531 - val_loss: 50241.3398 - val_mae: 50241.3398
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49811.9648 - mae: 49811.9648 - val_loss: 50241.6914 - val_mae: 50241.6914
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49621.5352 - mae: 49621.5352 - val_loss: 50227.7891 - val_mae: 50227.7891
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49652.5312 - mae: 49652.5312 - val_loss: 50216.0625 - val_mae: 50216.0625
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49956.6094 - mae: 49956.6094 - val_loss: 50221.2266 - val_mae: 50221.2266
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50278.4492 - mae: 50278.4492 - val_loss: 50219.6289 - val_mae: 50219.6289
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50312.8633 - mae: 50312.8633 - val_loss: 50226.6289 - val_mae: 50226.6289
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49498.7734 - mae: 49498.7734 - val_loss: 50221.7305 - val_mae: 50221.7305
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49846.9805 - mae: 49846.9805 - val_loss: 50203.9805 - val_mae: 50203.9805
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49898.8242 - mae: 49898.8242 - val_loss: 50213.9492 - val_mae: 50213.9492
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49655.4492 - mae: 49655.4492 - val_loss: 50204.4531 - val_mae: 50204.4531
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49561.8555 - mae: 49561.8555 - val_loss: 50202.6875 - val_mae: 50202.6875
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49518.9336 - mae: 49518.9336 - val_loss: 50201.6445 - val_mae: 50201.6445
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49865.7812 - mae: 49865.7812 - val_loss: 50195.8867 - val_mae: 50195.8867
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49542.3906 - mae: 49542.3906 - val_loss: 50198.6914 - val_mae: 50198.6914
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49719.7852 - mae: 49719.7852 - val_loss: 50199.3047 - val_mae: 50199.3047
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49266.0117 - mae: 49266.0117 - val_loss: 50188.0391 - val_mae: 50188.0391
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49299.8164 - mae: 49299.8164 - val_loss: 50190.8047 - val_mae: 50190.8047
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49568.0352 - mae: 49568.0352 - val_loss: 50193.0703 - val_mae: 50193.0703
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - loss: 49310.8281 - mae: 49310.8281 - val_loss: 50200.4375 - val_mae: 50200.4375
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - loss: 49345.5000 - mae: 49345.5000 - val_loss: 50188.0117 - val_mae: 50188.0117
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - loss: 49373.4531 - mae: 49373.4531 - val_loss: 50197.2031 - val_mae: 50197.2031
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - loss: 49402.4023 - mae: 49402.4023 - val_loss: 50197.3359 - val_mae: 50197.3359
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - loss: 49418.5391 - mae: 49418.5391 - val_loss: 50195.0508 - val_mae: 50195.0508
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - loss: 48878.8516 - mae: 48878.8516 - val_loss: 50202.8750 - val_mae: 50202.8750
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50377.4180 - mae: 50377.4180 - val_loss: 50187.1836 - val_mae: 50187.1836
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49098.4492 - mae: 49098.4492 - val_loss: 50192.8555 - val_mae: 50192.8555
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49786.2617 - mae: 49786.2617 - val_loss: 50194.9336 - val_mae: 50194.9336
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - loss: 49690.3828 - mae: 49690.3828 - val_loss: 50199.8945 - val_mae: 50199.8945
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - loss: 49652.6641 - mae: 49652.6641 - val_loss: 50191.7305 - val_mae: 50191.7305
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - loss: 49400.0820 - mae: 49400.0820 - val_loss: 50195.1523 - val_mae: 50195.1523
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - loss: 49310.4570 - mae: 49310.4570 - val_loss: 50198.5664 - val_mae: 50198.5664
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - loss: 49660.4141 - mae: 49660.4141 - val_loss: 50198.0117 - val_mae: 50198.0117
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49058.1836 - mae: 49058.1836 - val_loss: 50202.5859 - val_mae: 50202.5859
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - loss: 49274.8711 - mae: 49274.8711 - val_loss: 50194.6680 - val_mae: 50194.6680
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - loss: 49575.2266 - mae: 49575.2266 - val_loss: 50200.9922 - val_mae: 50200.9922

In [52]:
%reload_ext tensorboard

In [64]:
%tensorboard --logdir="regression_log1/fit20240917-182622"

Reusing TensorBoard on port 6016 (pid 20328), started 0:00:04 ago. (Use '!kill 20328' to kill it.)

In [68]:
## Evaluate model on the rest data
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae} ')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 466us/step - loss: 51122.7969 - mae: 51122.7969
Test MAE : 50187.18359375

In [69]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.